#if !defined(INSTANCINGBUFFERDECL_INCLUDED)

UNITY_INSTANCING_BUFFER_START(InstanceProperties)
	UNITY_DEFINE_INSTANCED_PROP(float4, _BaseColor)
#if defined(_HAS_VAT_RIGID) || defined(_HAS_VAT_SOFT) || defined(_HAS_VAT_FLUID)
	UNITY_DEFINE_INSTANCED_PROP(float, _VATCursor)
#endif
UNITY_INSTANCING_BUFFER_END(InstanceProperties)
#define INSTANCINGBUFFERDECL_INCLUDED
#endif