# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_android
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

INCLUDES += -I../../ExternalLibs/Runtime -I../../ExternalLibs/Runtime/include -I../../ExternalLibs/Runtime/include/license/UnityStore -I../../Plugins/CodecImage_EXR -I../../Plugins/CodecImage_EXR/include -I../../Plugins/CodecImage_EXR/OpenEXR-2.3.0 -I../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf -I../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmThread -I../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/Imath -I../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/Iex -I../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/Half -I../../ExternalLibs/Runtime/libs/zlib-1.2.8
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS +=
LDDEPS +=
define LINKCMD
  $(SILENT) $(RM) -f $@
  $(SILENT) $(AR) -rcs $@ $(OBJECTS)
endef
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug_android)
ifeq ($(origin CC), default)
  CC = $(EASYPATH)/arm-linux-androideabi-clang
endif
ifeq ($(origin CXX), default)
  CXX = $(EASYPATH)/arm-linux-androideabi-clang++
endif
ifeq ($(origin AR), default)
  AR = $(EASYPATH)/arm-linux-androideabi-ar
endif
TARGETDIR = ../../ExternalLibs/Runtime/bin/UnityStore/gmake_android
TARGET = $(TARGETDIR)/libPK-Plugin_CodecImage_EXR_d.a
OBJDIR = ../intermediate/UnityStore/GM/android/Debug/PK-Plugin_CodecImage_EXR
DEFINES += -D_DEBUG -DIMATH_NAMESPACE=PK_Imath -DILMTHREAD_NAMESPACE=PK_IlmThread -DOPENEXR_IMF_NAMESPACE=PK_Imf -DIEX_NAMESPACE=PK_Iex -DZ_PREFIX -DZ_PREFIX_CUSTOM=pk_z_
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) $(ADDITIONAL_FLAGS) -march=armv7-a -mfloat-abi=softfp -Wshadow -Wundef -fno-omit-frame-pointer -O2 -fPIC -fno-strict-aliasing -g -fno-unsigned-char -Wall -Wextra -MP -pipe -Winvalid-pch -fno-math-errno -fno-trapping-math -ggdb -mfpu=neon -pipe
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) $(ADDITIONAL_FLAGS) -march=armv7-a -mfloat-abi=softfp -Wshadow -Wundef -fno-omit-frame-pointer -O2 -fPIC -fno-strict-aliasing -g -fno-unsigned-char -Wall -Wextra -std=gnu++0x -fvisibility-inlines-hidden -fvisibility=hidden -Winvalid-pch -fno-math-errno -fno-trapping-math -ggdb -mfpu=neon -pipe
ALL_LDFLAGS += $(LDFLAGS)

else ifeq ($(config),debug_android64)
ifeq ($(origin CC), default)
  CC = $(EASYPATH64)/aarch64-linux-android-clang
endif
ifeq ($(origin CXX), default)
  CXX = $(EASYPATH64)/aarch64-linux-android-clang++
endif
ifeq ($(origin AR), default)
  AR = $(EASYPATH64)/aarch64-linux-android-ar
endif
TARGETDIR = ../../ExternalLibs/Runtime/bin/UnityStore/gmake_android64
TARGET = $(TARGETDIR)/libPK-Plugin_CodecImage_EXR_d.a
OBJDIR = ../intermediate/UnityStore/GM/android64/Debug/PK-Plugin_CodecImage_EXR
DEFINES += -D_DEBUG -DIMATH_NAMESPACE=PK_Imath -DILMTHREAD_NAMESPACE=PK_IlmThread -DOPENEXR_IMF_NAMESPACE=PK_Imf -DIEX_NAMESPACE=PK_Iex -DZ_PREFIX -DZ_PREFIX_CUSTOM=pk_z_
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) $(ADDITIONAL_FLAGS64) -march=armv8-a -Wshadow -Wundef -fno-omit-frame-pointer -O2 -fPIC -fno-strict-aliasing -g -fno-unsigned-char -Wall -Wextra -MP -pipe -Winvalid-pch -fno-math-errno -fno-trapping-math -ggdb -pipe
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) $(ADDITIONAL_FLAGS64) -march=armv8-a -Wshadow -Wundef -fno-omit-frame-pointer -O2 -fPIC -fno-strict-aliasing -g -fno-unsigned-char -Wall -Wextra -std=gnu++0x -fvisibility-inlines-hidden -fvisibility=hidden -Winvalid-pch -fno-math-errno -fno-trapping-math -ggdb -pipe
ALL_LDFLAGS += $(LDFLAGS)

else ifeq ($(config),release_android)
ifeq ($(origin CC), default)
  CC = $(EASYPATH)/arm-linux-androideabi-clang
endif
ifeq ($(origin CXX), default)
  CXX = $(EASYPATH)/arm-linux-androideabi-clang++
endif
ifeq ($(origin AR), default)
  AR = $(EASYPATH)/arm-linux-androideabi-ar
endif
TARGETDIR = ../../ExternalLibs/Runtime/bin/UnityStore/gmake_android
TARGET = $(TARGETDIR)/libPK-Plugin_CodecImage_EXR_r.a
OBJDIR = ../intermediate/UnityStore/GM/android/Release/PK-Plugin_CodecImage_EXR
DEFINES += -DNDEBUG -DIMATH_NAMESPACE=PK_Imath -DILMTHREAD_NAMESPACE=PK_IlmThread -DOPENEXR_IMF_NAMESPACE=PK_Imf -DIEX_NAMESPACE=PK_Iex -DZ_PREFIX -DZ_PREFIX_CUSTOM=pk_z_
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) $(ADDITIONAL_FLAGS) -march=armv7-a -mfloat-abi=softfp -Wshadow -Wundef -fno-omit-frame-pointer -O3 -fPIC -fno-strict-aliasing -g -fno-unsigned-char -Wall -Wextra -MP -pipe -Winvalid-pch -fno-math-errno -fno-trapping-math -mfpu=neon -pipe
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) $(ADDITIONAL_FLAGS) -march=armv7-a -mfloat-abi=softfp -Wshadow -Wundef -fno-omit-frame-pointer -O3 -fPIC -fno-strict-aliasing -g -fno-unsigned-char -Wall -Wextra -std=gnu++0x -fvisibility-inlines-hidden -fvisibility=hidden -Winvalid-pch -fno-math-errno -fno-trapping-math -mfpu=neon -pipe
ALL_LDFLAGS += $(LDFLAGS)

else ifeq ($(config),release_android64)
ifeq ($(origin CC), default)
  CC = $(EASYPATH64)/aarch64-linux-android-clang
endif
ifeq ($(origin CXX), default)
  CXX = $(EASYPATH64)/aarch64-linux-android-clang++
endif
ifeq ($(origin AR), default)
  AR = $(EASYPATH64)/aarch64-linux-android-ar
endif
TARGETDIR = ../../ExternalLibs/Runtime/bin/UnityStore/gmake_android64
TARGET = $(TARGETDIR)/libPK-Plugin_CodecImage_EXR_r.a
OBJDIR = ../intermediate/UnityStore/GM/android64/Release/PK-Plugin_CodecImage_EXR
DEFINES += -DNDEBUG -DIMATH_NAMESPACE=PK_Imath -DILMTHREAD_NAMESPACE=PK_IlmThread -DOPENEXR_IMF_NAMESPACE=PK_Imf -DIEX_NAMESPACE=PK_Iex -DZ_PREFIX -DZ_PREFIX_CUSTOM=pk_z_
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) $(ADDITIONAL_FLAGS64) -march=armv8-a -Wshadow -Wundef -fno-omit-frame-pointer -O3 -fPIC -fno-strict-aliasing -g -fno-unsigned-char -Wall -Wextra -MP -pipe -Winvalid-pch -fno-math-errno -fno-trapping-math -pipe
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) $(ADDITIONAL_FLAGS64) -march=armv8-a -Wshadow -Wundef -fno-omit-frame-pointer -O3 -fPIC -fno-strict-aliasing -g -fno-unsigned-char -Wall -Wextra -std=gnu++0x -fvisibility-inlines-hidden -fvisibility=hidden -Winvalid-pch -fno-math-errno -fno-trapping-math -pipe
ALL_LDFLAGS += $(LDFLAGS)

else ifeq ($(config),retail_android)
ifeq ($(origin CC), default)
  CC = $(EASYPATH)/arm-linux-androideabi-clang
endif
ifeq ($(origin CXX), default)
  CXX = $(EASYPATH)/arm-linux-androideabi-clang++
endif
ifeq ($(origin AR), default)
  AR = $(EASYPATH)/arm-linux-androideabi-ar
endif
TARGETDIR = ../../ExternalLibs/Runtime/bin/UnityStore/gmake_android
TARGET = $(TARGETDIR)/libPK-Plugin_CodecImage_EXR_s.a
OBJDIR = ../intermediate/UnityStore/GM/android/Retail/PK-Plugin_CodecImage_EXR
DEFINES += -DNDEBUG -DPK_RETAIL -DIMATH_NAMESPACE=PK_Imath -DILMTHREAD_NAMESPACE=PK_IlmThread -DOPENEXR_IMF_NAMESPACE=PK_Imf -DIEX_NAMESPACE=PK_Iex -DZ_PREFIX -DZ_PREFIX_CUSTOM=pk_z_
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) $(ADDITIONAL_FLAGS) -march=armv7-a -mfloat-abi=softfp -Wshadow -Wundef -fomit-frame-pointer -O3 -fPIC -fno-strict-aliasing -fno-unsigned-char -Wall -Wextra -MP -pipe -Winvalid-pch -fno-math-errno -fno-trapping-math -mfpu=neon -pipe
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) $(ADDITIONAL_FLAGS) -march=armv7-a -mfloat-abi=softfp -Wshadow -Wundef -fomit-frame-pointer -O3 -fPIC -fno-strict-aliasing -fno-unsigned-char -Wall -Wextra -std=gnu++0x -fvisibility-inlines-hidden -fvisibility=hidden -Winvalid-pch -fno-math-errno -fno-trapping-math -mfpu=neon -pipe
ALL_LDFLAGS += $(LDFLAGS) -s

else ifeq ($(config),retail_android64)
ifeq ($(origin CC), default)
  CC = $(EASYPATH64)/aarch64-linux-android-clang
endif
ifeq ($(origin CXX), default)
  CXX = $(EASYPATH64)/aarch64-linux-android-clang++
endif
ifeq ($(origin AR), default)
  AR = $(EASYPATH64)/aarch64-linux-android-ar
endif
TARGETDIR = ../../ExternalLibs/Runtime/bin/UnityStore/gmake_android64
TARGET = $(TARGETDIR)/libPK-Plugin_CodecImage_EXR_s.a
OBJDIR = ../intermediate/UnityStore/GM/android64/Retail/PK-Plugin_CodecImage_EXR
DEFINES += -DNDEBUG -DPK_RETAIL -DIMATH_NAMESPACE=PK_Imath -DILMTHREAD_NAMESPACE=PK_IlmThread -DOPENEXR_IMF_NAMESPACE=PK_Imf -DIEX_NAMESPACE=PK_Iex -DZ_PREFIX -DZ_PREFIX_CUSTOM=pk_z_
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) $(ADDITIONAL_FLAGS64) -march=armv8-a -Wshadow -Wundef -fomit-frame-pointer -O3 -fPIC -fno-strict-aliasing -fno-unsigned-char -Wall -Wextra -MP -pipe -Winvalid-pch -fno-math-errno -fno-trapping-math -pipe
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) $(ADDITIONAL_FLAGS64) -march=armv8-a -Wshadow -Wundef -fomit-frame-pointer -O3 -fPIC -fno-strict-aliasing -fno-unsigned-char -Wall -Wextra -std=gnu++0x -fvisibility-inlines-hidden -fvisibility=hidden -Winvalid-pch -fno-math-errno -fno-trapping-math -pipe
ALL_LDFLAGS += $(LDFLAGS) -s

#else
#  $(error "invalid configuration $(config)")
endif

# Per File Configurations
# #############################################

PERFILE_FLAGS_0 = $(ALL_CXXFLAGS) -fno-rtti -include pk_compiler_warnings.h
PERFILE_FLAGS_1 = $(ALL_CXXFLAGS) -w -fno-rtti -include pk_compiler_warnings.h
PERFILE_FLAGS_2 = $(ALL_CXXFLAGS) -w

# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/IexBaseExc.o
GENERATED += $(OBJDIR)/IexThrowErrnoExc.o
GENERATED += $(OBJDIR)/IlmThread.o
GENERATED += $(OBJDIR)/IlmThreadMutex.o
GENERATED += $(OBJDIR)/IlmThreadMutexPosix.o
GENERATED += $(OBJDIR)/IlmThreadPool.o
GENERATED += $(OBJDIR)/IlmThreadPosix.o
GENERATED += $(OBJDIR)/IlmThreadSemaphore.o
GENERATED += $(OBJDIR)/IlmThreadSemaphorePosix.o
GENERATED += $(OBJDIR)/ImathColorAlgo.o
GENERATED += $(OBJDIR)/ImathFun.o
GENERATED += $(OBJDIR)/ImathMatrixAlgo.o
GENERATED += $(OBJDIR)/ImathRandom.o
GENERATED += $(OBJDIR)/ImathVec.o
GENERATED += $(OBJDIR)/ImfAcesFile.o
GENERATED += $(OBJDIR)/ImfAttribute.o
GENERATED += $(OBJDIR)/ImfB44Compressor.o
GENERATED += $(OBJDIR)/ImfBoxAttribute.o
GENERATED += $(OBJDIR)/ImfCRgbaFile.o
GENERATED += $(OBJDIR)/ImfChannelList.o
GENERATED += $(OBJDIR)/ImfChannelListAttribute.o
GENERATED += $(OBJDIR)/ImfChromaticities.o
GENERATED += $(OBJDIR)/ImfChromaticitiesAttribute.o
GENERATED += $(OBJDIR)/ImfCompositeDeepScanLine.o
GENERATED += $(OBJDIR)/ImfCompressionAttribute.o
GENERATED += $(OBJDIR)/ImfCompressor.o
GENERATED += $(OBJDIR)/ImfConvert.o
GENERATED += $(OBJDIR)/ImfDeepCompositing.o
GENERATED += $(OBJDIR)/ImfDeepFrameBuffer.o
GENERATED += $(OBJDIR)/ImfDeepImageStateAttribute.o
GENERATED += $(OBJDIR)/ImfDeepScanLineInputFile.o
GENERATED += $(OBJDIR)/ImfDeepScanLineInputPart.o
GENERATED += $(OBJDIR)/ImfDeepScanLineOutputFile.o
GENERATED += $(OBJDIR)/ImfDeepScanLineOutputPart.o
GENERATED += $(OBJDIR)/ImfDeepTiledInputFile.o
GENERATED += $(OBJDIR)/ImfDeepTiledInputPart.o
GENERATED += $(OBJDIR)/ImfDeepTiledOutputFile.o
GENERATED += $(OBJDIR)/ImfDeepTiledOutputPart.o
GENERATED += $(OBJDIR)/ImfDoubleAttribute.o
GENERATED += $(OBJDIR)/ImfDwaCompressor.o
GENERATED += $(OBJDIR)/ImfEnvmap.o
GENERATED += $(OBJDIR)/ImfEnvmapAttribute.o
GENERATED += $(OBJDIR)/ImfFastHuf.o
GENERATED += $(OBJDIR)/ImfFloatAttribute.o
GENERATED += $(OBJDIR)/ImfFloatVectorAttribute.o
GENERATED += $(OBJDIR)/ImfFrameBuffer.o
GENERATED += $(OBJDIR)/ImfFramesPerSecond.o
GENERATED += $(OBJDIR)/ImfGenericInputFile.o
GENERATED += $(OBJDIR)/ImfGenericOutputFile.o
GENERATED += $(OBJDIR)/ImfHeader.o
GENERATED += $(OBJDIR)/ImfHuf.o
GENERATED += $(OBJDIR)/ImfIO.o
GENERATED += $(OBJDIR)/ImfInputFile.o
GENERATED += $(OBJDIR)/ImfInputPart.o
GENERATED += $(OBJDIR)/ImfInputPartData.o
GENERATED += $(OBJDIR)/ImfIntAttribute.o
GENERATED += $(OBJDIR)/ImfKeyCode.o
GENERATED += $(OBJDIR)/ImfKeyCodeAttribute.o
GENERATED += $(OBJDIR)/ImfLineOrderAttribute.o
GENERATED += $(OBJDIR)/ImfLut.o
GENERATED += $(OBJDIR)/ImfMatrixAttribute.o
GENERATED += $(OBJDIR)/ImfMisc.o
GENERATED += $(OBJDIR)/ImfMultiPartInputFile.o
GENERATED += $(OBJDIR)/ImfMultiPartOutputFile.o
GENERATED += $(OBJDIR)/ImfMultiView.o
GENERATED += $(OBJDIR)/ImfOpaqueAttribute.o
GENERATED += $(OBJDIR)/ImfOutputFile.o
GENERATED += $(OBJDIR)/ImfOutputPart.o
GENERATED += $(OBJDIR)/ImfOutputPartData.o
GENERATED += $(OBJDIR)/ImfPartType.o
GENERATED += $(OBJDIR)/ImfPizCompressor.o
GENERATED += $(OBJDIR)/ImfPreviewImage.o
GENERATED += $(OBJDIR)/ImfPreviewImageAttribute.o
GENERATED += $(OBJDIR)/ImfPxr24Compressor.o
GENERATED += $(OBJDIR)/ImfRational.o
GENERATED += $(OBJDIR)/ImfRationalAttribute.o
GENERATED += $(OBJDIR)/ImfRgbaFile.o
GENERATED += $(OBJDIR)/ImfRgbaYca.o
GENERATED += $(OBJDIR)/ImfRle.o
GENERATED += $(OBJDIR)/ImfRleCompressor.o
GENERATED += $(OBJDIR)/ImfScanLineInputFile.o
GENERATED += $(OBJDIR)/ImfStandardAttributes.o
GENERATED += $(OBJDIR)/ImfStdIO.o
GENERATED += $(OBJDIR)/ImfStringAttribute.o
GENERATED += $(OBJDIR)/ImfStringVectorAttribute.o
GENERATED += $(OBJDIR)/ImfSystemSpecific.o
GENERATED += $(OBJDIR)/ImfTestFile.o
GENERATED += $(OBJDIR)/ImfThreading.o
GENERATED += $(OBJDIR)/ImfTileDescriptionAttribute.o
GENERATED += $(OBJDIR)/ImfTileOffsets.o
GENERATED += $(OBJDIR)/ImfTiledInputFile.o
GENERATED += $(OBJDIR)/ImfTiledInputPart.o
GENERATED += $(OBJDIR)/ImfTiledMisc.o
GENERATED += $(OBJDIR)/ImfTiledOutputFile.o
GENERATED += $(OBJDIR)/ImfTiledOutputPart.o
GENERATED += $(OBJDIR)/ImfTiledRgbaFile.o
GENERATED += $(OBJDIR)/ImfTimeCode.o
GENERATED += $(OBJDIR)/ImfTimeCodeAttribute.o
GENERATED += $(OBJDIR)/ImfVecAttribute.o
GENERATED += $(OBJDIR)/ImfVersion.o
GENERATED += $(OBJDIR)/ImfWav.o
GENERATED += $(OBJDIR)/ImfZip.o
GENERATED += $(OBJDIR)/ImfZipCompressor.o
GENERATED += $(OBJDIR)/exr_load.o
GENERATED += $(OBJDIR)/exr_main.o
GENERATED += $(OBJDIR)/exr_save.o
GENERATED += $(OBJDIR)/half.o
OBJECTS += $(OBJDIR)/IexBaseExc.o
OBJECTS += $(OBJDIR)/IexThrowErrnoExc.o
OBJECTS += $(OBJDIR)/IlmThread.o
OBJECTS += $(OBJDIR)/IlmThreadMutex.o
OBJECTS += $(OBJDIR)/IlmThreadMutexPosix.o
OBJECTS += $(OBJDIR)/IlmThreadPool.o
OBJECTS += $(OBJDIR)/IlmThreadPosix.o
OBJECTS += $(OBJDIR)/IlmThreadSemaphore.o
OBJECTS += $(OBJDIR)/IlmThreadSemaphorePosix.o
OBJECTS += $(OBJDIR)/ImathColorAlgo.o
OBJECTS += $(OBJDIR)/ImathFun.o
OBJECTS += $(OBJDIR)/ImathMatrixAlgo.o
OBJECTS += $(OBJDIR)/ImathRandom.o
OBJECTS += $(OBJDIR)/ImathVec.o
OBJECTS += $(OBJDIR)/ImfAcesFile.o
OBJECTS += $(OBJDIR)/ImfAttribute.o
OBJECTS += $(OBJDIR)/ImfB44Compressor.o
OBJECTS += $(OBJDIR)/ImfBoxAttribute.o
OBJECTS += $(OBJDIR)/ImfCRgbaFile.o
OBJECTS += $(OBJDIR)/ImfChannelList.o
OBJECTS += $(OBJDIR)/ImfChannelListAttribute.o
OBJECTS += $(OBJDIR)/ImfChromaticities.o
OBJECTS += $(OBJDIR)/ImfChromaticitiesAttribute.o
OBJECTS += $(OBJDIR)/ImfCompositeDeepScanLine.o
OBJECTS += $(OBJDIR)/ImfCompressionAttribute.o
OBJECTS += $(OBJDIR)/ImfCompressor.o
OBJECTS += $(OBJDIR)/ImfConvert.o
OBJECTS += $(OBJDIR)/ImfDeepCompositing.o
OBJECTS += $(OBJDIR)/ImfDeepFrameBuffer.o
OBJECTS += $(OBJDIR)/ImfDeepImageStateAttribute.o
OBJECTS += $(OBJDIR)/ImfDeepScanLineInputFile.o
OBJECTS += $(OBJDIR)/ImfDeepScanLineInputPart.o
OBJECTS += $(OBJDIR)/ImfDeepScanLineOutputFile.o
OBJECTS += $(OBJDIR)/ImfDeepScanLineOutputPart.o
OBJECTS += $(OBJDIR)/ImfDeepTiledInputFile.o
OBJECTS += $(OBJDIR)/ImfDeepTiledInputPart.o
OBJECTS += $(OBJDIR)/ImfDeepTiledOutputFile.o
OBJECTS += $(OBJDIR)/ImfDeepTiledOutputPart.o
OBJECTS += $(OBJDIR)/ImfDoubleAttribute.o
OBJECTS += $(OBJDIR)/ImfDwaCompressor.o
OBJECTS += $(OBJDIR)/ImfEnvmap.o
OBJECTS += $(OBJDIR)/ImfEnvmapAttribute.o
OBJECTS += $(OBJDIR)/ImfFastHuf.o
OBJECTS += $(OBJDIR)/ImfFloatAttribute.o
OBJECTS += $(OBJDIR)/ImfFloatVectorAttribute.o
OBJECTS += $(OBJDIR)/ImfFrameBuffer.o
OBJECTS += $(OBJDIR)/ImfFramesPerSecond.o
OBJECTS += $(OBJDIR)/ImfGenericInputFile.o
OBJECTS += $(OBJDIR)/ImfGenericOutputFile.o
OBJECTS += $(OBJDIR)/ImfHeader.o
OBJECTS += $(OBJDIR)/ImfHuf.o
OBJECTS += $(OBJDIR)/ImfIO.o
OBJECTS += $(OBJDIR)/ImfInputFile.o
OBJECTS += $(OBJDIR)/ImfInputPart.o
OBJECTS += $(OBJDIR)/ImfInputPartData.o
OBJECTS += $(OBJDIR)/ImfIntAttribute.o
OBJECTS += $(OBJDIR)/ImfKeyCode.o
OBJECTS += $(OBJDIR)/ImfKeyCodeAttribute.o
OBJECTS += $(OBJDIR)/ImfLineOrderAttribute.o
OBJECTS += $(OBJDIR)/ImfLut.o
OBJECTS += $(OBJDIR)/ImfMatrixAttribute.o
OBJECTS += $(OBJDIR)/ImfMisc.o
OBJECTS += $(OBJDIR)/ImfMultiPartInputFile.o
OBJECTS += $(OBJDIR)/ImfMultiPartOutputFile.o
OBJECTS += $(OBJDIR)/ImfMultiView.o
OBJECTS += $(OBJDIR)/ImfOpaqueAttribute.o
OBJECTS += $(OBJDIR)/ImfOutputFile.o
OBJECTS += $(OBJDIR)/ImfOutputPart.o
OBJECTS += $(OBJDIR)/ImfOutputPartData.o
OBJECTS += $(OBJDIR)/ImfPartType.o
OBJECTS += $(OBJDIR)/ImfPizCompressor.o
OBJECTS += $(OBJDIR)/ImfPreviewImage.o
OBJECTS += $(OBJDIR)/ImfPreviewImageAttribute.o
OBJECTS += $(OBJDIR)/ImfPxr24Compressor.o
OBJECTS += $(OBJDIR)/ImfRational.o
OBJECTS += $(OBJDIR)/ImfRationalAttribute.o
OBJECTS += $(OBJDIR)/ImfRgbaFile.o
OBJECTS += $(OBJDIR)/ImfRgbaYca.o
OBJECTS += $(OBJDIR)/ImfRle.o
OBJECTS += $(OBJDIR)/ImfRleCompressor.o
OBJECTS += $(OBJDIR)/ImfScanLineInputFile.o
OBJECTS += $(OBJDIR)/ImfStandardAttributes.o
OBJECTS += $(OBJDIR)/ImfStdIO.o
OBJECTS += $(OBJDIR)/ImfStringAttribute.o
OBJECTS += $(OBJDIR)/ImfStringVectorAttribute.o
OBJECTS += $(OBJDIR)/ImfSystemSpecific.o
OBJECTS += $(OBJDIR)/ImfTestFile.o
OBJECTS += $(OBJDIR)/ImfThreading.o
OBJECTS += $(OBJDIR)/ImfTileDescriptionAttribute.o
OBJECTS += $(OBJDIR)/ImfTileOffsets.o
OBJECTS += $(OBJDIR)/ImfTiledInputFile.o
OBJECTS += $(OBJDIR)/ImfTiledInputPart.o
OBJECTS += $(OBJDIR)/ImfTiledMisc.o
OBJECTS += $(OBJDIR)/ImfTiledOutputFile.o
OBJECTS += $(OBJDIR)/ImfTiledOutputPart.o
OBJECTS += $(OBJDIR)/ImfTiledRgbaFile.o
OBJECTS += $(OBJDIR)/ImfTimeCode.o
OBJECTS += $(OBJDIR)/ImfTimeCodeAttribute.o
OBJECTS += $(OBJDIR)/ImfVecAttribute.o
OBJECTS += $(OBJDIR)/ImfVersion.o
OBJECTS += $(OBJDIR)/ImfWav.o
OBJECTS += $(OBJDIR)/ImfZip.o
OBJECTS += $(OBJDIR)/ImfZipCompressor.o
OBJECTS += $(OBJDIR)/exr_load.o
OBJECTS += $(OBJDIR)/exr_main.o
OBJECTS += $(OBJDIR)/exr_save.o
OBJECTS += $(OBJDIR)/half.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking PK-Plugin_CodecImage_EXR
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning PK-Plugin_CodecImage_EXR
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) del /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/half.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/Half/half.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IexBaseExc.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/Iex/IexBaseExc.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IexThrowErrnoExc.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/Iex/IexThrowErrnoExc.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfAcesFile.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfAcesFile.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfB44Compressor.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfB44Compressor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfBoxAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfBoxAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfCRgbaFile.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfCRgbaFile.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfChannelList.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfChannelList.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfChannelListAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfChannelListAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfChromaticities.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfChromaticities.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfChromaticitiesAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfChromaticitiesAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfCompositeDeepScanLine.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfCompositeDeepScanLine.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfCompressionAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfCompressionAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfCompressor.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfCompressor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfConvert.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfConvert.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfDeepCompositing.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfDeepCompositing.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfDeepFrameBuffer.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfDeepFrameBuffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfDeepImageStateAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfDeepImageStateAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfDeepScanLineInputFile.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfDeepScanLineInputFile.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfDeepScanLineInputPart.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfDeepScanLineInputPart.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfDeepScanLineOutputFile.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfDeepScanLineOutputFile.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfDeepScanLineOutputPart.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfDeepScanLineOutputPart.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfDeepTiledInputFile.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfDeepTiledInputFile.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfDeepTiledInputPart.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfDeepTiledInputPart.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfDeepTiledOutputFile.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfDeepTiledOutputFile.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfDeepTiledOutputPart.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfDeepTiledOutputPart.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfDoubleAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfDoubleAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfDwaCompressor.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfDwaCompressor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfEnvmap.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfEnvmap.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfEnvmapAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfEnvmapAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfFastHuf.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfFastHuf.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfFloatAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfFloatAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfFloatVectorAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfFloatVectorAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfFrameBuffer.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfFrameBuffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfFramesPerSecond.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfFramesPerSecond.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfGenericInputFile.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfGenericInputFile.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfGenericOutputFile.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfGenericOutputFile.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfHeader.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfHeader.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfHuf.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfHuf.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfIO.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfIO.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfInputFile.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfInputFile.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfInputPart.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfInputPart.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfInputPartData.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfInputPartData.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfIntAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfIntAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfKeyCode.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfKeyCode.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfKeyCodeAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfKeyCodeAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfLineOrderAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfLineOrderAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfLut.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfLut.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfMatrixAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfMatrixAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfMisc.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfMisc.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfMultiPartInputFile.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfMultiPartInputFile.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfMultiPartOutputFile.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfMultiPartOutputFile.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfMultiView.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfMultiView.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfOpaqueAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfOpaqueAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfOutputFile.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfOutputFile.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfOutputPart.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfOutputPart.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfOutputPartData.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfOutputPartData.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfPartType.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfPartType.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfPizCompressor.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfPizCompressor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfPreviewImage.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfPreviewImage.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfPreviewImageAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfPreviewImageAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfPxr24Compressor.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfPxr24Compressor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfRational.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfRational.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfRationalAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfRationalAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfRgbaFile.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfRgbaFile.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfRgbaYca.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfRgbaYca.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfRle.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfRle.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfRleCompressor.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfRleCompressor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfScanLineInputFile.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfScanLineInputFile.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfStandardAttributes.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfStandardAttributes.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfStdIO.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfStdIO.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfStringAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfStringAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfStringVectorAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfStringVectorAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfSystemSpecific.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfSystemSpecific.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfTestFile.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfTestFile.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfThreading.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfThreading.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfTileDescriptionAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfTileDescriptionAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfTileOffsets.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfTileOffsets.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfTiledInputFile.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfTiledInputFile.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfTiledInputPart.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfTiledInputPart.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfTiledMisc.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfTiledMisc.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfTiledOutputFile.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfTiledOutputFile.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfTiledOutputPart.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfTiledOutputPart.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfTiledRgbaFile.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfTiledRgbaFile.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfTimeCode.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfTimeCode.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfTimeCodeAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfTimeCodeAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfVecAttribute.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfVecAttribute.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfVersion.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfVersion.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfWav.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfWav.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfZip.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfZip.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImfZipCompressor.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmImf/ImfZipCompressor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IlmThread.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmThread/IlmThread.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IlmThreadMutex.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmThread/IlmThreadMutex.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IlmThreadMutexPosix.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmThread/IlmThreadMutexPosix.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IlmThreadPool.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmThread/IlmThreadPool.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IlmThreadPosix.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmThread/IlmThreadPosix.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IlmThreadSemaphore.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmThread/IlmThreadSemaphore.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IlmThreadSemaphorePosix.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/IlmThread/IlmThreadSemaphorePosix.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImathColorAlgo.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/Imath/ImathColorAlgo.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImathFun.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/Imath/ImathFun.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImathMatrixAlgo.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/Imath/ImathMatrixAlgo.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImathRandom.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/Imath/ImathRandom.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImathVec.o: ../../Plugins/CodecImage_EXR/OpenEXR-2.3.0/Imath/ImathVec.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_2) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/exr_load.o: ../../Plugins/CodecImage_EXR/exr_load.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_1) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/exr_main.o: ../../Plugins/CodecImage_EXR/exr_main.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_1) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/exr_save.o: ../../Plugins/CodecImage_EXR/exr_save.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_1) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif
